services:
  markdown-pdf:
    build: .
    ports:
      - "4444:3000"
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - CHROME_LAUNCH_OPTIONS=--no-sandbox --disable-dev-shm-usage --disable-gpu
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    tmpfs:
      - /tmp:exec,mode=1777
      - /dev/shm:size=2g
    shm_size: '2gb'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped