services:
  markdown-pdf:
    build: .
    ports:
      - "3033:3000"
    environment:
      - NODE_ENV=production
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped